image_field_in_field_detail: 1
field_in_field_list : 9
comment_example_avatar: https://i.pinimg.com/564x/97/bb/06/97bb067e30ff6b89f4fbb7b9141025ca.jpg
format_date: "%H:%M"
admin:
  booking_fields_pagy: 20
  time_format: "%H:%M"
  date_format: "%m-%d-%Y"
